const productJsonMock = [
  {
    'id': 337,
    'name': 'Customised Vintage Fit Ripped Jeans',
    'slug': 'customised-vintage-fit-ripped-jeans-2',
    'permalink':
        'https://demo.mstore.io/product/customised-vintage-fit-ripped-jeans-2/',
    'date_created': '2024-06-20T16:55:22',
    'date_created_gmt': '2024-06-20T09:55:22',
    'date_modified': '2024-12-31T16:02:51',
    'date_modified_gmt': '2024-12-31T09:02:51',
    'type': 'simple',
    'status': 'publish',
    'featured': false,
    'catalog_visibility': 'visible',
    'description':
        "<ul>\n<li>Non-stretch denim</li>\n<li>Button fly</li>\n<li>Classic five pocket styling</li>\n<li>Ripped detail</li>\n<li>Regular fit - true to size</li>\n<li>100% Cotton</li>\n<li>Machine wash</li>\n<li>100% Cotton</li>\n<li>Our model wears a UK 8/EU 36/US 4 and is 178 cm/5'10” tall</li>\n</ul>\n",
    'short_description': '',
    'sku': '',
    'price': 20,
    'regular_price': 20,
    'sale_price': null,
    'date_on_sale_from': null,
    'date_on_sale_from_gmt': null,
    'date_on_sale_to': null,
    'date_on_sale_to_gmt': null,
    'on_sale': false,
    'purchasable': true,
    'total_sales': 11,
    'virtual': false,
    'downloadable': false,
    'downloads': [],
    'download_limit': 0,
    'download_expiry': 0,
    'external_url': '',
    'button_text': '',
    'tax_status': 'taxable',
    'tax_class': '',
    'manage_stock': false,
    'stock_quantity': null,
    'in_stock': true,
    'backorders': 'no',
    'backorders_allowed': false,
    'backordered': false,
    'sold_individually': false,
    'weight': '',
    'dimensions': {'length': '', 'width': '', 'height': ''},
    'shipping_required': true,
    'shipping_taxable': true,
    'shipping_class': '',
    'shipping_class_id': 0,
    'reviews_allowed': true,
    'average_rating': '0.00',
    'rating_count': 0,
    'upsell_ids': [],
    'cross_sell_ids': [],
    'parent_id': 0,
    'purchase_note': '',
    'categories': [
      {'id': 24, 'name': 'Clothing', 'slug': 'clothing'},
      {'id': 18, 'name': 'Jeans', 'slug': 'jeans'},
      {'id': 17, 'name': 'Women', 'slug': 'women'},
    ],
    'tags': [
      {'id': 52, 'name': 'jean', 'slug': 'jean'},
      {'id': 53, 'name': 'women', 'slug': 'women'},
    ],
    'images': [
      {
        'id': 51,
        'date_created': '2024-06-20T22:48:33',
        'date_created_gmt': '2024-06-20T08:48:33',
        'date_modified': '2024-06-20T22:48:33',
        'date_modified_gmt': '2024-06-20T08:48:33',
        'src':
            'https://demo.mstore.io/wp-content/uploads/2024/06/image4xxl-4.jpg',
        'name': 'image4xxl-4.jpg',
        'alt': '',
        'position': 0,
      },
      {
        'id': 404,
        'date_created': '2024-06-20T23:57:23',
        'date_created_gmt': '2024-06-20T09:57:23',
        'date_modified': '2024-06-20T23:57:23',
        'date_modified_gmt': '2024-06-20T09:57:23',
        'src':
            'https://demo.mstore.io/wp-content/uploads/2024/06/image3xxl-4.jpg',
        'name': 'image3xxl-4.jpg',
        'alt': '',
        'position': 1,
      },
      {
        'id': 49,
        'date_created': '2024-06-20T22:48:26',
        'date_created_gmt': '2024-06-20T08:48:26',
        'date_modified': '2024-06-20T22:48:26',
        'date_modified_gmt': '2024-06-20T08:48:26',
        'src':
            'https://demo.mstore.io/wp-content/uploads/2024/06/image2xxl-5.jpg',
        'name': 'image2xxl-5.jpg',
        'alt': '',
        'position': 2,
      },
      {
        'id': 48,
        'date_created': '2024-06-20T22:48:24',
        'date_created_gmt': '2024-06-20T08:48:24',
        'date_modified': '2024-06-20T22:48:24',
        'date_modified_gmt': '2024-06-20T08:48:24',
        'src':
            'https://demo.mstore.io/wp-content/uploads/2024/06/image1xxl-5.jpg',
        'name': 'image1xxl-5.jpg',
        'alt': '',
        'position': 3,
      }
    ],
    'attributes': [],
    'default_attributes': [],
    'variations': [],
    'grouped_products': [],
    'menu_order': 26,
    'price_html':
        '<span class="woocs_price_code" data-currency="" data-redraw-id="6776a0c6cf07e"  data-product-id="337"><span class="woocommerce-Price-amount amount"><bdi>20,00<span class="woocommerce-Price-currencySymbol">&#36;</span></bdi></span></span>',
    'related_ids': [21, 32, 22, 25, 15],
    'meta_data': [
      {'id': 16120, 'key': 'slide_template', 'value': 'default'},
      {'id': 16121, 'key': 'sbg_selected_sidebar_replacement', 'value': ''},
      {'id': 16122, 'key': '_wpml_media_duplicate', 'value': ''},
      {'id': 16123, 'key': '_wpml_media_featured', 'value': ''},
      {'id': 16124, 'key': 'mwb_product_points_enable', 'value': ''},
      {'id': 16125, 'key': 'mwb_points_product_value', 'value': ''},
      {'id': 16126, 'key': '_minmax_product_min_quantity', 'value': ''},
      {'id': 16127, 'key': '_minmax_product_max_quantity', 'value': ''},
      {'id': 16128, 'key': '_minmax_product_min_price', 'value': ''},
      {'id': 16129, 'key': '_minmax_product_max_price', 'value': ''},
      {'id': 16130, 'key': '_minmax_ignore_global', 'value': ''},
      {'id': 16131, 'key': '_wcml_custom_prices_status', 'value': ''},
      {'id': 16132, 'key': '_product_addons_exclude_global', 'value': '0'},
      {'id': 16133, 'key': 'woopos_product_last_set_stock', 'value': ''},
      {'id': 16134, 'key': 'ihc_mb_type', 'value': ''},
      {'id': 16135, 'key': 'ihc_mb_who', 'value': ''},
      {'id': 16136, 'key': 'ihc_mb_block_type', 'value': ''},
      {'id': 16137, 'key': 'ihc_mb_redirect_to', 'value': ''},
      {'id': 16138, 'key': 'ihc_replace_content', 'value': ''},
      {'id': 16139, 'key': 'ihc_drip_content', 'value': ''},
      {'id': 16140, 'key': 'ihc_drip_start_type', 'value': ''},
      {'id': 16141, 'key': 'ihc_drip_end_type', 'value': ''},
      {'id': 16142, 'key': 'ihc_drip_start_numeric_type', 'value': ''},
      {'id': 16143, 'key': 'ihc_drip_start_numeric_value', 'value': ''},
      {'id': 16144, 'key': 'ihc_drip_end_numeric_type', 'value': ''},
      {'id': 16145, 'key': 'ihc_drip_end_numeric_value', 'value': ''},
      {'id': 16146, 'key': 'ihc_drip_start_certain_date', 'value': ''},
      {'id': 16147, 'key': 'ihc_drip_end_certain_date', 'value': ''},
      {'id': 16148, 'key': '_mstore_video_url', 'value': ''},
      {'id': 16149, 'key': '_mstore_video_title', 'value': ''},
      {'id': 16150, 'key': '_mstore_video_description', 'value': ''},
      {'id': 16151, 'key': '_wcmmq_min_qty', 'value': ''},
      {'id': 16152, 'key': '_wcmmq_max_qty', 'value': ''},
      {'id': 16153, 'key': '_wcmmq_step', 'value': ''},
      {'id': 16154, 'key': '_wcmmq_disable', 'value': ''},
      {'id': 16155, 'key': '_wcmmq_enable', 'value': ''},
      {'id': 16156, 'key': 'wholesale_customer_wholesale_price', 'value': ''},
      {
        'id': 16157,
        'key': 'wholesale_customer_have_wholesale_price',
        'value': '',
      },
      {'id': 16158, 'key': 'onesignal_meta_box_present', 'value': '1'},
      {'id': 16159, 'key': 'onesignal_send_notification', 'value': ''},
      {
        'id': 16160,
        'key': 'algolia_searchable_posts_records_count',
        'value': '1',
      },
      {'id': 16161, 'key': '_wc_max_points_earned', 'value': ''},
      {'id': 16162, 'key': '_wc_min_points_earned', 'value': ''},
      {'id': 16163, 'key': '_cashback_type', 'value': ''},
      {'id': 16164, 'key': '_cashback_amount', 'value': ''},
      {
        'id': 16165,
        'key': 'wwpp_post_meta_enable_quantity_discount_rule',
        'value': '',
      },
      {
        'id': 16166,
        'key':
            'wholesale_customer_variable_level_wholesale_minimum_order_quantity',
        'value': '',
      },
      {
        'id': 16167,
        'key':
            'wholesale_customer_variable_level_wholesale_order_quantity_step',
        'value': '',
      },
      {
        'id': 16168,
        'key': 'wwpp_ignore_cat_level_wholesale_discount',
        'value': '',
      },
      {
        'id': 16169,
        'key': 'wwpp_ignore_role_level_wholesale_discount',
        'value': '',
      },
      {'id': 16170, 'key': 'wwpp_product_hash', 'value': ''},
      {'id': 16171, 'key': '_wc_min_max_quantities_min_qty', 'value': ''},
      {'id': 16172, 'key': '_wc_min_max_quantities_max_qty', 'value': ''},
      {'id': 16173, 'key': '_wc_min_max_quantities_step', 'value': ''},
      {'id': 16174, 'key': '_wc_min_max_quantities_excluded', 'value': ''},
      {'id': 16175, 'key': '_wc_min_max_quantities_override', 'value': ''},
      {'id': 16176, 'key': 'yith_sl_show_find_in_stores', 'value': ''},
      {'id': 16177, 'key': 'yith_sl_override_global_settings', 'value': ''},
      {
        'id': 16178,
        'key': 'wwpp_product_wholesale_visibility_filter',
        'value': '',
      },
      {'id': 16179, 'key': '_wp_old_date', 'value': ''},
      {
        'id': 16180,
        'key': 'wholesale_customer_wholesale_minimum_order_quantity',
        'value': '',
      },
      {
        'id': 16181,
        'key': 'wholesale_customer_wholesale_order_quantity_step',
        'value': '',
      },
      {'id': 16182, 'key': '_min_variation_price', 'value': ''},
      {'id': 16183, 'key': '_max_variation_price', 'value': ''},
      {'id': 16184, 'key': '_min_price_variation_id', 'value': ''},
      {'id': 16185, 'key': '_max_price_variation_id', 'value': ''},
      {'id': 16186, 'key': '_min_variation_regular_price', 'value': ''},
      {'id': 16187, 'key': '_max_variation_regular_price', 'value': ''},
      {'id': 16188, 'key': '_min_regular_price_variation_id', 'value': ''},
      {'id': 16189, 'key': '_max_regular_price_variation_id', 'value': ''},
      {'id': 16190, 'key': '_min_variation_sale_price', 'value': ''},
      {'id': 16191, 'key': '_max_variation_sale_price', 'value': ''},
      {'id': 16192, 'key': '_min_sale_price_variation_id', 'value': ''},
      {'id': 16193, 'key': '_max_sale_price_variation_id', 'value': ''},
      {'id': 16194, 'key': 'mwb_wpr_variable_points', 'value': ''},
      {'id': 16195, 'key': '_ywbc_barcode_protocol', 'value': ''},
      {'id': 16196, 'key': '_ywbc_barcode_value', 'value': ''},
      {'id': 16197, 'key': '_ywbc_barcode_display_value', 'value': ''},
      {
        'id': 16198,
        'key': 'ywbc_barcode_display_value_custom_field',
        'value': '',
      },
      {'id': 16199, 'key': '_ywbc_barcode_image', 'value': ''},
      {'id': 16200, 'key': '_ywbc_barcode_filename', 'value': ''},
      {'id': 16201, 'key': '_wc_appointment_has_price_label', 'value': ''},
      {'id': 16202, 'key': '_wc_appointment_price_label', 'value': ''},
      {'id': 16203, 'key': '_wc_appointment_has_pricing', 'value': ''},
      {'id': 16204, 'key': '_wc_appointment_qty', 'value': ''},
      {'id': 16205, 'key': '_wc_appointment_qty_min', 'value': ''},
      {'id': 16206, 'key': '_wc_appointment_qty_max', 'value': ''},
      {'id': 16207, 'key': '_wc_appointment_duration_unit', 'value': ''},
      {'id': 16208, 'key': '_wc_appointment_duration', 'value': ''},
      {'id': 16209, 'key': '_wc_appointment_interval_unit', 'value': ''},
      {'id': 16210, 'key': '_wc_appointment_interval', 'value': ''},
      {
        'id': 16211,
        'key': '_wc_appointment_padding_duration_unit',
        'value': '',
      },
      {'id': 16212, 'key': '_wc_appointment_padding_duration', 'value': ''},
      {'id': 16213, 'key': '_wc_appointment_min_date_unit', 'value': ''},
      {'id': 16214, 'key': '_wc_appointment_min_date', 'value': ''},
      {'id': 16215, 'key': '_wc_appointment_max_date_unit', 'value': ''},
      {'id': 16216, 'key': '_wc_appointment_max_date', 'value': ''},
      {'id': 16217, 'key': '_wc_appointment_user_can_cancel', 'value': ''},
      {'id': 16218, 'key': '_wc_appointment_cancel_limit_unit', 'value': ''},
      {'id': 16219, 'key': '_wc_appointment_cancel_limit', 'value': ''},
      {'id': 16220, 'key': '_wc_appointment_user_can_reschedule', 'value': ''},
      {
        'id': 16221,
        'key': '_wc_appointment_reschedule_limit_unit',
        'value': '',
      },
      {'id': 16222, 'key': '_wc_appointment_reschedule_limit', 'value': ''},
      {
        'id': 16223,
        'key': '_wc_appointment_requires_confirmation',
        'value': '',
      },
      {'id': 16224, 'key': '_wc_appointment_customer_timezones', 'value': ''},
      {'id': 16225, 'key': '_wc_appointment_cal_color', 'value': ''},
      {'id': 16226, 'key': '_wc_appointment_availability_span', 'value': ''},
      {
        'id': 16227,
        'key': '_wc_appointment_availability_autoselect',
        'value': '',
      },
      {'id': 16228, 'key': '_wc_appointment_has_restricted_days', 'value': ''},
      {'id': 16229, 'key': '_wc_appointment_restricted_days', 'value': ''},
      {'id': 16230, 'key': '_wc_appointment_staff_label', 'value': ''},
      {'id': 16231, 'key': '_wc_appointment_staff_assignment', 'value': ''},
      {'id': 16232, 'key': '_wc_appointment_staff_nopref', 'value': ''},
      {'id': 16233, 'key': '_yith_wcbm_badge_from_date', 'value': ''},
      {'id': 16234, 'key': '_yith_wcbm_badge_to_date', 'value': ''},
      {'id': 16235, 'key': '_yith_wcbm_badge_schedule', 'value': '0'},
      {'id': 16236, 'key': '_product_url', 'value': ''},
      {'id': 16237, 'key': '_subscription_payment_sync_date', 'value': ''},
      {'id': 16238, 'key': 'easyweb_webnus_views', 'value': ''},
      {'id': 16239, 'key': '_video_url', 'value': ''},
      {'id': 16240, 'key': '_video_image_url', 'value': ''},
      {'id': 16241, 'key': '_min_max_variation_ids_hash', 'value': ''},
      {'id': 16242, 'key': '_subscription_limit', 'value': ''},
      {'id': 16243, 'key': '_subscription_one_time_shipping', 'value': ''},
      {'id': 16244, 'key': 'attr_label_translations', 'value': ''},
      {'id': 16245, 'key': '_wpas_done_all', 'value': ''},
      {'id': 16246, 'key': '_wp_attachment_metadata', 'value': ''},
      {'id': 16247, 'key': 'wpml_media_processed', 'value': '1'},
      {'id': 16248, 'key': '_wp_attached_file', 'value': ''},
      {'id': 16249, 'key': '_wcml_duplicate_of_variation', 'value': ''},
      {'id': 44519, 'key': 'onesignal_modify_title_and_content', 'value': ''},
      {'id': 44522, 'key': '_product_addons', 'value': []},
      {
        'id': '_yith_wcbm_badges',
        'key': '_yith_wcbm_badges',
        'value': [
          {
            'id': 652,
            'title': '',
            'enabled': 'yes',
            'type': 'css',
            'uploaded_image_id': '',
            'uploaded_image_width': 0,
            'image': '1.svg',
            'css': '8.svg',
            'advanced': '1.svg',
            'advanced_display': 'amount',
            'text': '<p>New!</p>',
            'background_color': '#e1542d',
            'text_color': '#FFFFFF',
            'size': {
              'dimensions': {'width': '150', 'height': '50'},
              'linked': 'no',
              'unit': 'px',
            },
            'padding': {
              'dimensions': {
                'top': '0',
                'right': '0',
                'bottom': '0',
                'left': '0',
              },
              'linked': 'no',
              'unit': 'px',
            },
            'border_radius': {
              'dimensions': {
                'top-left': '0',
                'top-right': '0',
                'bottom-right': '0',
                'bottom-left': '0',
              },
              'linked': 'no',
              'unit': 'px',
            },
            'margin': {
              'dimensions': {'top': 0, 'bottom': 0, 'right': 0, 'left': 0},
              'linked': 'no',
              'unit': 'px',
            },
            'opacity': 100,
            'rotation': {
              'x': '0',
              'x-input': '0',
              'y': '0',
              'y-input': '0',
              'z': '0',
              'z-input': '0',
            },
            'use_flip_text': 'no',
            'flip_text': 'vertical',
            'position_type': 'fixed',
            'anchor_point': 'top-left',
            'position_values': {
              'dimensions': {
                'top': '0',
                'bottom': '0',
                'right': '0',
                'left': '0',
              },
              'unit': 'px',
            },
            'position': 'top',
            'alignment': 'right',
            'scale_on_mobile': 1,
            'meta_data': [
              {'id': 42535, 'key': '_edit_lock', 'value': '1730693376:2'},
              {'id': 42536, 'key': '_edit_last', 'value': '2'},
            ],
          }
        ],
      },
      {
        'id': '_yith-wcbm-hide-on-single-product',
        'key': '_yith-wcbm-hide-on-single-product',
        'value': false,
      }
    ],
    'brands': [
      {'id': 58, 'name': 'Brands', 'slug': 'hi'},
    ],
    'is_purchased': false,
    'attributesData': [],
    'is_wallet_product': false,
    '_links': {
      'self': [
        {
          'href': 'https://demo.mstore.io/wp-json/wc/v2/products/337',
          'targetHints': {
            'allow': ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'],
          },
        }
      ],
      'collection': [
        {'href': 'https://demo.mstore.io/wp-json/wc/v2/products'},
      ],
    },
  },
  {
    'id': 325,
    'name': "Nylon Padded Pak'R Backpack",
    'slug': 'nylon-padded-pakr-backpack-2',
    'permalink': 'https://demo.mstore.io/product/nylon-padded-pakr-backpack-2/',
    'date_created': '2024-06-20T16:55:01',
    'date_created_gmt': '2024-06-20T09:55:01',
    'date_modified': '2024-12-31T16:02:51',
    'date_modified_gmt': '2024-12-31T09:02:51',
    'type': 'simple',
    'status': 'publish',
    'featured': false,
    'catalog_visibility': 'visible',
    'description':
        '<ul>\n<li>Smooth outer</li>\n<li>Grab handle</li>\n<li>Zip around opening</li>\n<li>Internal slip pocket</li>\n<li>Large zip pocket to exterior</li>\n<li>Branded patch to front</li>\n<li>Padded, adjustable shoulder straps</li>\n<li>Wipe with a damp cloth</li>\n<li>100% Polyamide</li>\n</ul>\n<p>&nbsp;</p>\n',
    'short_description': '',
    'sku': '',
    'price': 65,
    'regular_price': 65,
    'sale_price': null,
    'date_on_sale_from': null,
    'date_on_sale_from_gmt': null,
    'date_on_sale_to': null,
    'date_on_sale_to_gmt': null,
    'on_sale': false,
    'purchasable': true,
    'total_sales': 2,
    'virtual': false,
    'downloadable': false,
    'downloads': [],
    'download_limit': 0,
    'download_expiry': 0,
    'external_url': '',
    'button_text': '',
    'tax_status': 'taxable',
    'tax_class': '',
    'manage_stock': false,
    'stock_quantity': null,
    'in_stock': true,
    'backorders': 'no',
    'backorders_allowed': false,
    'backordered': false,
    'sold_individually': false,
    'weight': '',
    'dimensions': {'length': '', 'width': '', 'height': ''},
    'shipping_required': true,
    'shipping_taxable': true,
    'shipping_class': '',
    'shipping_class_id': 0,
    'reviews_allowed': true,
    'average_rating': '0.00',
    'rating_count': 0,
    'upsell_ids': [],
    'cross_sell_ids': [],
    'parent_id': 0,
    'purchase_note': '',
    'categories': [
      {'id': 37, 'name': 'Bag', 'slug': 'bag'},
      {'id': 36, 'name': 'Men', 'slug': 'men'},
    ],
    'tags': [],
    'images': [
      {
        'id': 176,
        'date_created': '2024-06-20T22:54:47',
        'date_created_gmt': '2024-06-20T08:54:47',
        'date_modified': '2024-06-20T22:54:47',
        'date_modified_gmt': '2024-06-20T08:54:47',
        'src':
            'https://demo.mstore.io/wp-content/uploads/2024/06/image1xxl-13.jpg',
        'name': 'image1xxl-13.jpg',
        'alt': '',
        'position': 0,
      },
      {
        'id': 177,
        'date_created': '2024-06-20T22:54:49',
        'date_created_gmt': '2024-06-20T08:54:49',
        'date_modified': '2024-06-20T22:54:49',
        'date_modified_gmt': '2024-06-20T08:54:49',
        'src':
            'https://demo.mstore.io/wp-content/uploads/2024/06/image3xxl-22-1.jpg',
        'name': 'image3xxl-22-1.jpg',
        'alt': '',
        'position': 1,
      },
      {
        'id': 178,
        'date_created': '2024-06-20T22:54:52',
        'date_created_gmt': '2024-06-20T08:54:52',
        'date_modified': '2024-06-20T22:54:52',
        'date_modified_gmt': '2024-06-20T08:54:52',
        'src':
            'https://demo.mstore.io/wp-content/uploads/2024/06/image2xxl-23.jpg',
        'name': 'image2xxl-23.jpg',
        'alt': '',
        'position': 2,
      }
    ],
    'attributes': [],
    'default_attributes': [],
    'variations': [],
    'grouped_products': [],
    'menu_order': 69,
    'price_html':
        '<span class="woocs_price_code" data-currency="" data-redraw-id="6776a0c6d51c5"  data-product-id="325"><span class="woocommerce-Price-amount amount"><bdi>65,00<span class="woocommerce-Price-currencySymbol">&#36;</span></bdi></span></span>',
    'related_ids': [98, 122, 83, 71, 70],
    'meta_data': [
      {'id': 15847, 'key': 'slide_template', 'value': 'default'},
      {'id': 15848, 'key': 'sbg_selected_sidebar_replacement', 'value': '0'},
      {'id': 15849, 'key': '_wpml_media_duplicate', 'value': ''},
      {'id': 15850, 'key': '_wpml_media_featured', 'value': ''},
      {'id': 15851, 'key': 'mwb_product_points_enable', 'value': 'yes'},
      {'id': 15852, 'key': 'mwb_points_product_value', 'value': '10'},
      {'id': 15853, 'key': '_minmax_product_min_quantity', 'value': ''},
      {'id': 15854, 'key': '_minmax_product_max_quantity', 'value': ''},
      {'id': 15855, 'key': '_minmax_product_min_price', 'value': ''},
      {'id': 15856, 'key': '_minmax_product_max_price', 'value': ''},
      {'id': 15857, 'key': '_minmax_ignore_global', 'value': ''},
      {'id': 15858, 'key': '_wcml_custom_prices_status', 'value': ''},
      {'id': 15859, 'key': '_product_addons_exclude_global', 'value': ''},
      {'id': 15860, 'key': 'woopos_product_last_set_stock', 'value': ''},
      {'id': 15861, 'key': 'ihc_mb_type', 'value': ''},
      {'id': 15862, 'key': 'ihc_mb_who', 'value': ''},
      {'id': 15863, 'key': 'ihc_mb_block_type', 'value': ''},
      {'id': 15864, 'key': 'ihc_mb_redirect_to', 'value': ''},
      {'id': 15865, 'key': 'ihc_replace_content', 'value': ''},
      {'id': 15866, 'key': 'ihc_drip_content', 'value': ''},
      {'id': 15867, 'key': 'ihc_drip_start_type', 'value': ''},
      {'id': 15868, 'key': 'ihc_drip_end_type', 'value': ''},
      {'id': 15869, 'key': 'ihc_drip_start_numeric_type', 'value': ''},
      {'id': 15870, 'key': 'ihc_drip_start_numeric_value', 'value': ''},
      {'id': 15871, 'key': 'ihc_drip_end_numeric_type', 'value': ''},
      {'id': 15872, 'key': 'ihc_drip_end_numeric_value', 'value': ''},
      {'id': 15873, 'key': 'ihc_drip_start_certain_date', 'value': ''},
      {'id': 15874, 'key': 'ihc_drip_end_certain_date', 'value': ''},
      {'id': 15875, 'key': '_mstore_video_url', 'value': ''},
      {'id': 15876, 'key': '_mstore_video_title', 'value': ''},
      {'id': 15877, 'key': '_mstore_video_description', 'value': ''},
      {'id': 15878, 'key': '_wcmmq_min_qty', 'value': ''},
      {'id': 15879, 'key': '_wcmmq_max_qty', 'value': ''},
      {'id': 15880, 'key': '_wcmmq_step', 'value': ''},
      {'id': 15881, 'key': '_wcmmq_disable', 'value': ''},
      {'id': 15882, 'key': '_wcmmq_enable', 'value': ''},
      {'id': 15883, 'key': 'wholesale_customer_wholesale_price', 'value': ''},
      {
        'id': 15884,
        'key': 'wholesale_customer_have_wholesale_price',
        'value': '',
      },
      {'id': 15885, 'key': 'onesignal_meta_box_present', 'value': ''},
      {'id': 15886, 'key': 'onesignal_send_notification', 'value': ''},
      {
        'id': 15887,
        'key': 'algolia_searchable_posts_records_count',
        'value': '',
      },
      {'id': 15888, 'key': '_wc_max_points_earned', 'value': ''},
      {'id': 15889, 'key': '_wc_min_points_earned', 'value': ''},
      {'id': 15890, 'key': '_cashback_type', 'value': ''},
      {'id': 15891, 'key': '_cashback_amount', 'value': ''},
      {
        'id': 15892,
        'key': 'wwpp_post_meta_enable_quantity_discount_rule',
        'value': '',
      },
      {
        'id': 15893,
        'key':
            'wholesale_customer_variable_level_wholesale_minimum_order_quantity',
        'value': '',
      },
      {
        'id': 15894,
        'key':
            'wholesale_customer_variable_level_wholesale_order_quantity_step',
        'value': '',
      },
      {
        'id': 15895,
        'key': 'wwpp_ignore_cat_level_wholesale_discount',
        'value': '',
      },
      {
        'id': 15896,
        'key': 'wwpp_ignore_role_level_wholesale_discount',
        'value': '',
      },
      {'id': 15897, 'key': 'wwpp_product_hash', 'value': ''},
      {'id': 15898, 'key': '_wc_min_max_quantities_min_qty', 'value': ''},
      {'id': 15899, 'key': '_wc_min_max_quantities_max_qty', 'value': ''},
      {'id': 15900, 'key': '_wc_min_max_quantities_step', 'value': ''},
      {'id': 15901, 'key': '_wc_min_max_quantities_excluded', 'value': ''},
      {'id': 15902, 'key': '_wc_min_max_quantities_override', 'value': ''},
      {'id': 15903, 'key': 'yith_sl_show_find_in_stores', 'value': ''},
      {'id': 15904, 'key': 'yith_sl_override_global_settings', 'value': ''},
      {
        'id': 15905,
        'key': 'wwpp_product_wholesale_visibility_filter',
        'value': '',
      },
      {'id': 15906, 'key': '_wp_old_date', 'value': ''},
      {
        'id': 15907,
        'key': 'wholesale_customer_wholesale_minimum_order_quantity',
        'value': '',
      },
      {
        'id': 15908,
        'key': 'wholesale_customer_wholesale_order_quantity_step',
        'value': '',
      },
      {'id': 15909, 'key': '_min_variation_price', 'value': ''},
      {'id': 15910, 'key': '_max_variation_price', 'value': ''},
      {'id': 15911, 'key': '_min_price_variation_id', 'value': ''},
      {'id': 15912, 'key': '_max_price_variation_id', 'value': ''},
      {'id': 15913, 'key': '_min_variation_regular_price', 'value': ''},
      {'id': 15914, 'key': '_max_variation_regular_price', 'value': ''},
      {'id': 15915, 'key': '_min_regular_price_variation_id', 'value': ''},
      {'id': 15916, 'key': '_max_regular_price_variation_id', 'value': ''},
      {'id': 15917, 'key': '_min_variation_sale_price', 'value': ''},
      {'id': 15918, 'key': '_max_variation_sale_price', 'value': ''},
      {'id': 15919, 'key': '_min_sale_price_variation_id', 'value': ''},
      {'id': 15920, 'key': '_max_sale_price_variation_id', 'value': ''},
      {'id': 15921, 'key': 'mwb_wpr_variable_points', 'value': ''},
      {'id': 15922, 'key': '_ywbc_barcode_protocol', 'value': ''},
      {'id': 15923, 'key': '_ywbc_barcode_value', 'value': ''},
      {'id': 15924, 'key': '_ywbc_barcode_display_value', 'value': ''},
      {
        'id': 15925,
        'key': 'ywbc_barcode_display_value_custom_field',
        'value': '',
      },
      {'id': 15926, 'key': '_ywbc_barcode_image', 'value': ''},
      {'id': 15927, 'key': '_ywbc_barcode_filename', 'value': ''},
      {'id': 15928, 'key': '_wc_appointment_has_price_label', 'value': ''},
      {'id': 15929, 'key': '_wc_appointment_price_label', 'value': ''},
      {'id': 15930, 'key': '_wc_appointment_has_pricing', 'value': ''},
      {'id': 15931, 'key': '_wc_appointment_qty', 'value': ''},
      {'id': 15932, 'key': '_wc_appointment_qty_min', 'value': ''},
      {'id': 15933, 'key': '_wc_appointment_qty_max', 'value': ''},
      {'id': 15934, 'key': '_wc_appointment_duration_unit', 'value': ''},
      {'id': 15935, 'key': '_wc_appointment_duration', 'value': ''},
      {'id': 15936, 'key': '_wc_appointment_interval_unit', 'value': ''},
      {'id': 15937, 'key': '_wc_appointment_interval', 'value': ''},
      {
        'id': 15938,
        'key': '_wc_appointment_padding_duration_unit',
        'value': '',
      },
      {'id': 15939, 'key': '_wc_appointment_padding_duration', 'value': ''},
      {'id': 15940, 'key': '_wc_appointment_min_date_unit', 'value': ''},
      {'id': 15941, 'key': '_wc_appointment_min_date', 'value': ''},
      {'id': 15942, 'key': '_wc_appointment_max_date_unit', 'value': ''},
      {'id': 15943, 'key': '_wc_appointment_max_date', 'value': ''},
      {'id': 15944, 'key': '_wc_appointment_user_can_cancel', 'value': ''},
      {'id': 15945, 'key': '_wc_appointment_cancel_limit_unit', 'value': ''},
      {'id': 15946, 'key': '_wc_appointment_cancel_limit', 'value': ''},
      {'id': 15947, 'key': '_wc_appointment_user_can_reschedule', 'value': ''},
      {
        'id': 15948,
        'key': '_wc_appointment_reschedule_limit_unit',
        'value': '',
      },
      {'id': 15949, 'key': '_wc_appointment_reschedule_limit', 'value': ''},
      {
        'id': 15950,
        'key': '_wc_appointment_requires_confirmation',
        'value': '',
      },
      {'id': 15951, 'key': '_wc_appointment_customer_timezones', 'value': ''},
      {'id': 15952, 'key': '_wc_appointment_cal_color', 'value': ''},
      {'id': 15953, 'key': '_wc_appointment_availability_span', 'value': ''},
      {
        'id': 15954,
        'key': '_wc_appointment_availability_autoselect',
        'value': '',
      },
      {'id': 15955, 'key': '_wc_appointment_has_restricted_days', 'value': ''},
      {'id': 15956, 'key': '_wc_appointment_restricted_days', 'value': ''},
      {'id': 15957, 'key': '_wc_appointment_staff_label', 'value': ''},
      {'id': 15958, 'key': '_wc_appointment_staff_assignment', 'value': ''},
      {'id': 15959, 'key': '_wc_appointment_staff_nopref', 'value': ''},
      {'id': 15960, 'key': '_yith_wcbm_badge_from_date', 'value': ''},
      {'id': 15961, 'key': '_yith_wcbm_badge_to_date', 'value': ''},
      {'id': 15962, 'key': '_yith_wcbm_badge_schedule', 'value': ''},
      {'id': 15963, 'key': '_product_url', 'value': ''},
      {'id': 15964, 'key': '_subscription_payment_sync_date', 'value': ''},
      {'id': 15965, 'key': 'easyweb_webnus_views', 'value': ''},
      {'id': 15966, 'key': '_video_url', 'value': ''},
      {'id': 15967, 'key': '_video_image_url', 'value': ''},
      {'id': 15968, 'key': '_min_max_variation_ids_hash', 'value': ''},
      {'id': 15969, 'key': '_subscription_limit', 'value': ''},
      {'id': 15970, 'key': '_subscription_one_time_shipping', 'value': ''},
      {'id': 15971, 'key': 'attr_label_translations', 'value': ''},
      {'id': 15972, 'key': '_wpas_done_all', 'value': ''},
      {'id': 15973, 'key': '_wp_attachment_metadata', 'value': ''},
      {'id': 15974, 'key': 'wpml_media_processed', 'value': ''},
      {'id': 15975, 'key': '_wp_attached_file', 'value': ''},
      {'id': 15976, 'key': '_wcml_duplicate_of_variation', 'value': ''},
      {'id': '_yith_wcbm_badges', 'key': '_yith_wcbm_badges', 'value': []},
      {
        'id': '_yith-wcbm-hide-on-single-product',
        'key': '_yith-wcbm-hide-on-single-product',
        'value': false,
      }
    ],
    'brands': [],
    'is_purchased': false,
    'attributesData': [],
    'is_wallet_product': false,
    '_links': {
      'self': [
        {
          'href': 'https://demo.mstore.io/wp-json/wc/v2/products/325',
          'targetHints': {
            'allow': ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'],
          },
        }
      ],
      'collection': [
        {'href': 'https://demo.mstore.io/wp-json/wc/v2/products'},
      ],
    },
  },
  {
    'id': 315,
    'name': "Flared 70'S Jean",
    'slug': 'flared-70s-jean-2',
    'permalink': 'https://demo.mstore.io/product/flared-70s-jean-2/',
    'date_created': '2024-06-20T16:54:39',
    'date_created_gmt': '2024-06-20T09:54:39',
    'date_modified': '2024-12-31T16:02:51',
    'date_modified_gmt': '2024-12-31T09:02:51',
    'type': 'variable',
    'status': 'publish',
    'featured': false,
    'catalog_visibility': 'visible',
    'description':
        "<ul>\n<li>Stretch denim</li>\n<li>Concealed zip fly</li>\n<li>Classic five pocket styling</li>\n<li>Flared fit - cut with a straight leg that flares at the ankle</li>\n<li>Machine wash</li>\n<li>86% Cotton, 12% Polyester, 2% Elastane</li>\n<li>Our model wears a UK 8/EU 34/US XS and is 175cm/5'9” tall</li>\n</ul>\n",
    'short_description': '',
    'sku': '',
    'price': 10,
    'regular_price': 10,
    'sale_price': null,
    'date_on_sale_from': null,
    'date_on_sale_from_gmt': null,
    'date_on_sale_to': null,
    'date_on_sale_to_gmt': null,
    'on_sale': false,
    'purchasable': false,
    'total_sales': 0,
    'virtual': false,
    'downloadable': false,
    'downloads': [],
    'download_limit': 0,
    'download_expiry': 0,
    'external_url': '',
    'button_text': '',
    'tax_status': 'taxable',
    'tax_class': '',
    'manage_stock': false,
    'stock_quantity': null,
    'in_stock': false,
    'backorders': 'no',
    'backorders_allowed': false,
    'backordered': false,
    'sold_individually': false,
    'weight': '',
    'dimensions': {'length': '', 'width': '', 'height': ''},
    'shipping_required': true,
    'shipping_taxable': true,
    'shipping_class': '',
    'shipping_class_id': 0,
    'reviews_allowed': true,
    'average_rating': '0.00',
    'rating_count': 0,
    'upsell_ids': [],
    'cross_sell_ids': [],
    'parent_id': 0,
    'purchase_note': '',
    'categories': [
      {'id': 18, 'name': 'Jeans', 'slug': 'jeans'},
      {'id': 17, 'name': 'Women', 'slug': 'women'},
    ],
    'tags': [],
    'images': [
      {
        'id': 403,
        'date_created': '2024-06-20T23:57:18',
        'date_created_gmt': '2024-06-20T09:57:18',
        'date_modified': '2024-06-20T23:57:18',
        'date_modified_gmt': '2024-06-20T09:57:18',
        'src':
            'https://demo.mstore.io/wp-content/uploads/2024/06/image1xxl.jpg',
        'name': 'image1xxl.jpg',
        'alt': '',
        'position': 0,
      }
    ],
    'attributes': [
      {
        'id': 2,
        'name': 'size',
        'slug': 'pa_size',
        'position': 0,
        'visible': false,
        'variation': false,
        'options': ['L', 'M', 'S', 'XL'],
      }
    ],
    'default_attributes': [],
    'variations': [],
    'grouped_products': [],
    'menu_order': 40,
    'price_html': '',
    'related_ids': [27, 42, 20, 23, 24],
    'meta_data': [
      {'id': 15713, 'key': 'slide_template', 'value': 'default'},
      {'id': 15714, 'key': 'sbg_selected_sidebar_replacement', 'value': '0'},
      {'id': 15715, 'key': '_wpml_media_duplicate', 'value': ''},
      {'id': 15716, 'key': '_wpml_media_featured', 'value': ''},
      {'id': 15717, 'key': 'mwb_product_points_enable', 'value': 'yes'},
      {'id': 15718, 'key': 'mwb_points_product_value', 'value': '10'},
      {'id': 15719, 'key': '_minmax_product_min_quantity', 'value': ''},
      {'id': 15720, 'key': '_minmax_product_max_quantity', 'value': ''},
      {'id': 15721, 'key': '_minmax_product_min_price', 'value': ''},
      {'id': 15722, 'key': '_minmax_product_max_price', 'value': ''},
      {'id': 15723, 'key': '_minmax_ignore_global', 'value': ''},
      {'id': 15724, 'key': '_wcml_custom_prices_status', 'value': ''},
      {'id': 15725, 'key': '_product_addons_exclude_global', 'value': ''},
      {'id': 15726, 'key': 'woopos_product_last_set_stock', 'value': ''},
      {'id': 15727, 'key': 'ihc_mb_type', 'value': ''},
      {'id': 15728, 'key': 'ihc_mb_who', 'value': ''},
      {'id': 15729, 'key': 'ihc_mb_block_type', 'value': ''},
      {'id': 15730, 'key': 'ihc_mb_redirect_to', 'value': ''},
      {'id': 15731, 'key': 'ihc_replace_content', 'value': ''},
      {'id': 15732, 'key': 'ihc_drip_content', 'value': ''},
      {'id': 15733, 'key': 'ihc_drip_start_type', 'value': ''},
      {'id': 15734, 'key': 'ihc_drip_end_type', 'value': ''},
      {'id': 15735, 'key': 'ihc_drip_start_numeric_type', 'value': ''},
      {'id': 15736, 'key': 'ihc_drip_start_numeric_value', 'value': ''},
      {'id': 15737, 'key': 'ihc_drip_end_numeric_type', 'value': ''},
      {'id': 15738, 'key': 'ihc_drip_end_numeric_value', 'value': ''},
      {'id': 15739, 'key': 'ihc_drip_start_certain_date', 'value': ''},
      {'id': 15740, 'key': 'ihc_drip_end_certain_date', 'value': ''},
      {'id': 15741, 'key': '_mstore_video_url', 'value': ''},
      {'id': 15742, 'key': '_mstore_video_title', 'value': ''},
      {'id': 15743, 'key': '_mstore_video_description', 'value': ''},
      {'id': 15744, 'key': '_wcmmq_min_qty', 'value': ''},
      {'id': 15745, 'key': '_wcmmq_max_qty', 'value': ''},
      {'id': 15746, 'key': '_wcmmq_step', 'value': ''},
      {'id': 15747, 'key': '_wcmmq_disable', 'value': ''},
      {'id': 15748, 'key': '_wcmmq_enable', 'value': ''},
      {'id': 15749, 'key': 'wholesale_customer_wholesale_price', 'value': ''},
      {
        'id': 15750,
        'key': 'wholesale_customer_have_wholesale_price',
        'value': '',
      },
      {'id': 15751, 'key': 'onesignal_meta_box_present', 'value': ''},
      {'id': 15752, 'key': 'onesignal_send_notification', 'value': ''},
      {
        'id': 15753,
        'key': 'algolia_searchable_posts_records_count',
        'value': '',
      },
      {'id': 15754, 'key': '_wc_max_points_earned', 'value': ''},
      {'id': 15755, 'key': '_wc_min_points_earned', 'value': ''},
      {'id': 15756, 'key': '_cashback_type', 'value': ''},
      {'id': 15757, 'key': '_cashback_amount', 'value': ''},
      {
        'id': 15758,
        'key': 'wwpp_post_meta_enable_quantity_discount_rule',
        'value': '',
      },
      {
        'id': 15759,
        'key':
            'wholesale_customer_variable_level_wholesale_minimum_order_quantity',
        'value': '',
      },
      {
        'id': 15760,
        'key':
            'wholesale_customer_variable_level_wholesale_order_quantity_step',
        'value': '',
      },
      {
        'id': 15761,
        'key': 'wwpp_ignore_cat_level_wholesale_discount',
        'value': '',
      },
      {
        'id': 15762,
        'key': 'wwpp_ignore_role_level_wholesale_discount',
        'value': '',
      },
      {'id': 15763, 'key': 'wwpp_product_hash', 'value': ''},
      {'id': 15764, 'key': '_wc_min_max_quantities_min_qty', 'value': ''},
      {'id': 15765, 'key': '_wc_min_max_quantities_max_qty', 'value': ''},
      {'id': 15766, 'key': '_wc_min_max_quantities_step', 'value': ''},
      {'id': 15767, 'key': '_wc_min_max_quantities_excluded', 'value': ''},
      {'id': 15768, 'key': '_wc_min_max_quantities_override', 'value': ''},
      {'id': 15769, 'key': 'yith_sl_show_find_in_stores', 'value': ''},
      {'id': 15770, 'key': 'yith_sl_override_global_settings', 'value': ''},
      {
        'id': 15771,
        'key': 'wwpp_product_wholesale_visibility_filter',
        'value': '',
      },
      {'id': 15772, 'key': '_wp_old_date', 'value': ''},
      {
        'id': 15773,
        'key': 'wholesale_customer_wholesale_minimum_order_quantity',
        'value': '',
      },
      {
        'id': 15774,
        'key': 'wholesale_customer_wholesale_order_quantity_step',
        'value': '',
      },
      {'id': 15775, 'key': '_min_variation_price', 'value': '40'},
      {'id': 15776, 'key': '_max_variation_price', 'value': '40'},
      {'id': 15777, 'key': '_min_price_variation_id', 'value': '15'},
      {'id': 15778, 'key': '_max_price_variation_id', 'value': '15'},
      {'id': 15779, 'key': '_min_variation_regular_price', 'value': '40'},
      {'id': 15780, 'key': '_max_variation_regular_price', 'value': '40'},
      {'id': 15781, 'key': '_min_regular_price_variation_id', 'value': '15'},
      {'id': 15782, 'key': '_max_regular_price_variation_id', 'value': '15'},
      {'id': 15783, 'key': '_min_variation_sale_price', 'value': ''},
      {'id': 15784, 'key': '_max_variation_sale_price', 'value': ''},
      {'id': 15785, 'key': '_min_sale_price_variation_id', 'value': ''},
      {'id': 15786, 'key': '_max_sale_price_variation_id', 'value': ''},
      {'id': 15787, 'key': 'mwb_wpr_variable_points', 'value': ''},
      {'id': 15788, 'key': '_ywbc_barcode_protocol', 'value': ''},
      {'id': 15789, 'key': '_ywbc_barcode_value', 'value': ''},
      {'id': 15790, 'key': '_ywbc_barcode_display_value', 'value': ''},
      {
        'id': 15791,
        'key': 'ywbc_barcode_display_value_custom_field',
        'value': '',
      },
      {'id': 15792, 'key': '_ywbc_barcode_image', 'value': ''},
      {'id': 15793, 'key': '_ywbc_barcode_filename', 'value': ''},
      {'id': 15794, 'key': '_wc_appointment_has_price_label', 'value': ''},
      {'id': 15795, 'key': '_wc_appointment_price_label', 'value': ''},
      {'id': 15796, 'key': '_wc_appointment_has_pricing', 'value': ''},
      {'id': 15797, 'key': '_wc_appointment_qty', 'value': ''},
      {'id': 15798, 'key': '_wc_appointment_qty_min', 'value': ''},
      {'id': 15799, 'key': '_wc_appointment_qty_max', 'value': ''},
      {'id': 15800, 'key': '_wc_appointment_duration_unit', 'value': ''},
      {'id': 15801, 'key': '_wc_appointment_duration', 'value': ''},
      {'id': 15802, 'key': '_wc_appointment_interval_unit', 'value': ''},
      {'id': 15803, 'key': '_wc_appointment_interval', 'value': ''},
      {
        'id': 15804,
        'key': '_wc_appointment_padding_duration_unit',
        'value': '',
      },
      {'id': 15805, 'key': '_wc_appointment_padding_duration', 'value': ''},
      {'id': 15806, 'key': '_wc_appointment_min_date_unit', 'value': ''},
      {'id': 15807, 'key': '_wc_appointment_min_date', 'value': ''},
      {'id': 15808, 'key': '_wc_appointment_max_date_unit', 'value': ''},
      {'id': 15809, 'key': '_wc_appointment_max_date', 'value': ''},
      {'id': 15810, 'key': '_wc_appointment_user_can_cancel', 'value': ''},
      {'id': 15811, 'key': '_wc_appointment_cancel_limit_unit', 'value': ''},
      {'id': 15812, 'key': '_wc_appointment_cancel_limit', 'value': ''},
      {'id': 15813, 'key': '_wc_appointment_user_can_reschedule', 'value': ''},
      {
        'id': 15814,
        'key': '_wc_appointment_reschedule_limit_unit',
        'value': '',
      },
      {'id': 15815, 'key': '_wc_appointment_reschedule_limit', 'value': ''},
      {
        'id': 15816,
        'key': '_wc_appointment_requires_confirmation',
        'value': '',
      },
      {'id': 15817, 'key': '_wc_appointment_customer_timezones', 'value': ''},
      {'id': 15818, 'key': '_wc_appointment_cal_color', 'value': ''},
      {'id': 15819, 'key': '_wc_appointment_availability_span', 'value': ''},
      {
        'id': 15820,
        'key': '_wc_appointment_availability_autoselect',
        'value': '',
      },
      {'id': 15821, 'key': '_wc_appointment_has_restricted_days', 'value': ''},
      {'id': 15822, 'key': '_wc_appointment_restricted_days', 'value': ''},
      {'id': 15823, 'key': '_wc_appointment_staff_label', 'value': ''},
      {'id': 15824, 'key': '_wc_appointment_staff_assignment', 'value': ''},
      {'id': 15825, 'key': '_wc_appointment_staff_nopref', 'value': ''},
      {'id': 15826, 'key': '_yith_wcbm_badge_from_date', 'value': ''},
      {'id': 15827, 'key': '_yith_wcbm_badge_to_date', 'value': ''},
      {'id': 15828, 'key': '_yith_wcbm_badge_schedule', 'value': ''},
      {'id': 15829, 'key': '_product_url', 'value': ''},
      {'id': 15830, 'key': '_subscription_payment_sync_date', 'value': ''},
      {'id': 15831, 'key': 'easyweb_webnus_views', 'value': ''},
      {'id': 15832, 'key': '_video_url', 'value': ''},
      {'id': 15833, 'key': '_video_image_url', 'value': ''},
      {'id': 15834, 'key': '_min_max_variation_ids_hash', 'value': ''},
      {'id': 15835, 'key': '_subscription_limit', 'value': ''},
      {'id': 15836, 'key': '_subscription_one_time_shipping', 'value': ''},
      {'id': 15837, 'key': 'attr_label_translations', 'value': ''},
      {'id': 15838, 'key': '_wpas_done_all', 'value': ''},
      {'id': 15839, 'key': '_wp_attachment_metadata', 'value': ''},
      {'id': 15840, 'key': 'wpml_media_processed', 'value': ''},
      {'id': 15841, 'key': '_wp_attached_file', 'value': ''},
      {'id': 15842, 'key': '_wcml_duplicate_of_variation', 'value': ''},
      {
        'id': '_yith_wcbm_badges',
        'key': '_yith_wcbm_badges',
        'value': [
          {
            'id': 652,
            'title': '',
            'enabled': 'yes',
            'type': 'css',
            'uploaded_image_id': '',
            'uploaded_image_width': 0,
            'image': '1.svg',
            'css': '8.svg',
            'advanced': '1.svg',
            'advanced_display': 'amount',
            'text': '<p>New!</p>',
            'background_color': '#e1542d',
            'text_color': '#FFFFFF',
            'size': {
              'dimensions': {'width': '150', 'height': '50'},
              'linked': 'no',
              'unit': 'px',
            },
            'padding': {
              'dimensions': {
                'top': '0',
                'right': '0',
                'bottom': '0',
                'left': '0',
              },
              'linked': 'no',
              'unit': 'px',
            },
            'border_radius': {
              'dimensions': {
                'top-left': '0',
                'top-right': '0',
                'bottom-right': '0',
                'bottom-left': '0',
              },
              'linked': 'no',
              'unit': 'px',
            },
            'margin': {
              'dimensions': {'top': 0, 'bottom': 0, 'right': 0, 'left': 0},
              'linked': 'no',
              'unit': 'px',
            },
            'opacity': 100,
            'rotation': {
              'x': '0',
              'x-input': '0',
              'y': '0',
              'y-input': '0',
              'z': '0',
              'z-input': '0',
            },
            'use_flip_text': 'no',
            'flip_text': 'vertical',
            'position_type': 'fixed',
            'anchor_point': 'top-left',
            'position_values': {
              'dimensions': {
                'top': '0',
                'bottom': '0',
                'right': '0',
                'left': '0',
              },
              'unit': 'px',
            },
            'position': 'top',
            'alignment': 'right',
            'scale_on_mobile': 1,
            'meta_data': [
              {'id': 42535, 'key': '_edit_lock', 'value': '1730693376:2'},
              {'id': 42536, 'key': '_edit_last', 'value': '2'},
            ],
          }
        ],
      },
      {
        'id': '_yith-wcbm-hide-on-single-product',
        'key': '_yith-wcbm-hide-on-single-product',
        'value': false,
      }
    ],
    'brands': [],
    'is_purchased': false,
    'attributesData': [
      {
        'id': 2,
        'name': 'pa_size',
        'options': [
          {
            'term_id': 45,
            'name': 'L',
            'slug': 'l',
            'term_group': 0,
            'term_taxonomy_id': 45,
            'taxonomy': 'pa_size',
            'description': '',
            'parent': 0,
            'count': 14,
            'filter': 'raw',
          },
          {
            'term_id': 39,
            'name': 'M',
            'slug': 'm',
            'term_group': 0,
            'term_taxonomy_id': 39,
            'taxonomy': 'pa_size',
            'description': '',
            'parent': 0,
            'count': 15,
            'filter': 'raw',
          },
          {
            'term_id': 40,
            'name': 'S',
            'slug': 's',
            'term_group': 0,
            'term_taxonomy_id': 40,
            'taxonomy': 'pa_size',
            'description': '',
            'parent': 0,
            'count': 15,
            'filter': 'raw',
          },
          {
            'term_id': 41,
            'name': 'XL',
            'slug': 'xl',
            'term_group': 0,
            'term_taxonomy_id': 41,
            'taxonomy': 'pa_size',
            'description': '',
            'parent': 0,
            'count': 13,
            'filter': 'raw',
          }
        ],
        'position': 0,
        'visible': false,
        'variation': false,
        'is_visible': 0,
        'is_variation': 0,
        'is_taxonomy': 1,
        'value': '',
        'label': 'size',
        'is_image_type': false,
      }
    ],
    'is_wallet_product': false,
    '_links': {
      'self': [
        {
          'href': 'https://demo.mstore.io/wp-json/wc/v2/products/315',
          'targetHints': {
            'allow': ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'],
          },
        }
      ],
      'collection': [
        {'href': 'https://demo.mstore.io/wp-json/wc/v2/products'},
      ],
    },
  },
];

const filtersConfigMock = {
  'categories': {
    'filters': [
      {
        'selectorType': 'getValueByKey',
        'filterBy': null,
        'key': 'categories',
        'operator': null,
        'value': null,
      },
      {
        'selectorType': 'getItemsFromWhere',
        'filterBy': 'value',
        'key': 'name',
        'operator': 'notEqual',
        'value': 'Women',
      },
      {
        'selectorType': 'getValueFromWhere',
        'filterBy': 'value',
        'key': 'name',
        'operator': 'isNotEmpty',
        'value': null,
      },
      {
        'selectorType': 'join',
        'filterBy': null,
        'key': null,
        'operator': null,
        'value': ', ',
      }
    ],
  },
  'tags': {
    'filters': [
      {
        'selectorType': 'getValueByKey',
        'filterBy': null,
        'key': 'tags',
        'operator': null,
        'value': null,
      },
      {
        'selectorType': 'getValueFromWhere',
        'filterBy': 'value',
        'key': 'name',
        'operator': 'isNotEmpty',
        'value': null,
      },
      {
        'selectorType': 'join',
        'filterBy': null,
        'key': null,
        'operator': null,
        'value': ', ',
      }
    ],
  },
};
